services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - ${DBPORT}:${DBPORT}
    volumes:
      - pg:/var/lib/postgresql/data
  rondelli_studio:
    container_name: rondelli_studio
    build: .
    command: ["sh", "-c","npx prisma db push && npm run dev"]
    ports:
      - 5000:5000
    env_file:
      - .env
    
    depends_on:
      - postgres
volumes:
  pg:
