services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    env_file:
     - .env
    ports:
      - 5433:5432
    volumes:
      - pg:/var/lib/postgresql/data
